(define (curry function @)
    (lambda (@)
        (if (= (length (get 'parameters @)) (length @))
            (apply function params)
            (curry function @)
            )
        )
    )

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define env this)
    (define (iter expr)
         (if (not (eof?)) (begin (eval expr env) (iter (readExpr))))
         )
    (iter (readExpr))
    )