#!/bin/bash

TASK_DIR=".."
SOL_DIR="./expected"
OUT_DIR="./output"

function test_task
{
    for f in task$1.*
    do
        scam -r "$TASK_DIR"/task$1.scm $f > "$OUT_DIR"/$f.mine
	diff "$OUT_DIR"/$f.mine "$SOL_DIR"/$f.expected
    done
}

TASKS="1 2 3 4 5 7 8"

for task in $TASKS
do
    test_task $task
done
