(define (addSpaces num)
    (define (iter x)
        (if (= x 0)
            ""
            (string+ (iter (- x 1)) " ")
            )
        )
    (string+ (iter num))
    )

(define (crazyTriangle left right)
    (lambda (levels)
        (define (getValue level index)
            (cond
                ((<= index 0) left)
                ((>= index (- level 1)) right)
                (else
                    (+ (getValue (- level 1) (- index 1)) (getValue (- level 1) index))
                    )
                )
            )
        (define (iterPrintValues level index)
            (cond
                ((>= index (- level 1)) "")
                (else
                    (string+ "" (+ (getValue (- level 1) (- index 1)) (getValue (- level 1) index)) " " (iterPrintValues level (+ index 1)))
                    )
                )
            )
        (define (iterPrint level)
            (cond
                ((= level 1) (string+ (addSpaces (- levels 1)) left "\n"))
                ((= level 2) (string+ (iterPrint 1) (addSpaces (- levels 2)) left " " right "\n"))
                (else (string+ (iterPrint (- level 1)) (addSpaces (- levels level)) left " " (iterPrintValues level 1) right "\n"))
                )
            )
        (print (iterPrint levels))
        )
    )

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define left (readInt))
    (define right (readInt))
    (define levels (readInt))
    (println "((crazyTriangle " left " " right ") " levels ")")
    ((crazyTriangle left right) levels)
    )
