(define (S function start stop prev)
    (define (iter i n value)
        (if (>= i n)
            (+ value (function i))
            (iter (+ i 1) n (+ value (function i)))
            )
        )
    (iter start stop prev)
    )

(define (w function i)
    (cond
        ((= i 0) (function i))
        (else
            (define sMinus1 (S function 0 (- i 1) 0))
            (define s (S function i i sMinus1))
            (define sPlus1 (S function (+ i 1) (+ i 1) s))
            (/ (- (* sPlus1 sMinus1) (* s s)) (+ (- sPlus1 (* 2 s)) sMinus1))
            )
        )
    )

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define argFunction (eval (readExpr) this))
    (define arg1 (readExpr))
    (println "(S " argFunction " " arg1 ") is " (fmt "%.15f" (S argFunction 0 arg1 0)))
    (println "(w " argFunction " " arg1 ") is " (fmt "%.15f" (w argFunction arg1)))
    )
