(define (ecfr x)
    (define (recur i)
        (if (> i x)
            0
            (/ 1 (+ 1 (/ 1 (+ (* 2 i) (/ 1 (+ 1 (recur (+ i 1))))))))
            )
        )
    (+ 2.0 (recur 1.0))
    )

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define arg1 (readInt))
    (println "(ecfr " arg1 ") is " (fmt "%.25f" (ecfr arg1)))
    )
