(define (power base power)
    (define (iter x n)
        (cond
            ((= n 1) x)
            ((= n 0) 1)
            (else
                (* x (iter x (- n 1)))
                )
            )
        )
    (iter base power)
    )

(define (root-n n)
    (lambda (x)
        (define (close? y oldY)
            (< (abs (- y oldY)) 0.00001)
            )
        (define (improve y)
            (/ (+ (* (- n 1) y) (/ x (power y (- n 1)))) n)
            )
        (define (iter y oldY)
            (if (close? y oldY)
                y
                (iter (improve y) y)
                )
            )
        (if (= x 0)
            0
            (iter 1.0 0.0)
            )
        )
    )

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define root (readInt))
    (define x (readInt))
    (println "((root-n " root ") " x ") is " (fmt "%.15f" ((root-n root) x)))
    )
