(define (curry function)
    (lambda (a)
        (lambda (b)
            (lambda (c)
                (lambda (d)
                    (function a b c d)
                    )
                )
            )
        )
    )

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define argFunction (eval (readExpr) this))
    (define arg1 (readInt))
    (define arg2 (readInt))
    (define arg3 (readInt))
    (define arg4 (readInt))
    (println "(((((curry " argFunction ") " arg1 ") " arg2 ") " arg3 ") " arg4 ") is " (((((curry argFunction) arg1) arg2) arg3) arg4))
    )
