(define (ecfi x)
    (define (iter term value)
        (cond
            ((<= term 0) value)
            (else (iter (+ term 1) (/ 1 (+ 1 (/ 1 (+ (* 2 term) (/ 1 (+ 1 value)))))))))
            )
        )
    (+ 2 (iter x 0)
    )

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define arg1 (readInt))
    (println "(ecfi " arg1 ") is " (fmt "%.25f" (ecfi arg1)))
    )
