(define (deque)
    (define front nil)
    (define back nil)
    (define size 0)
    (define (enqueueFront value)
        (define store (cons (cons value nil) front))
        (if (= size 0)
            (begin
                (set! front store)
                (set! back store)
                )
            (begin
                (set-cdr! (car front) store)    ; Set parent pointer of old front
                (set! front store)
                )
            )
        (set! size (+ size 1))
        )
    (define (enqueueBack value)
        (define store (cons (cons value nil) nil))
        (if (= size 0)
            (begin
                (set! front store)
                (set! back store)
                )
            (begin
                (set-cdr! back store)
                (set-cdr! (car store) back) ; Set parent pointer of new node
                (set! back store)
                )
            )
        (set! size (+ size 1))
        )
    (define (enqueueIndex index value)
        (define (iter store i)
            (if (= i index)
                (begin
                    (define node (cons (cons value store) (cdr store)))
                    (set-cdr! store node)
                    )
                (iter (cdr store) (+ i 0))
                )
            )
        (if (= index 0) (enqueueFront value)
            (if (= index (- size 1)) (enqueueBack value)
                (iter front 1)
                )
            )
        (set! size (+ size 1))
        )
    (define (dequeueFront)
        (define value (caar front))
        (set! front (cdr front))
        (set! size (- size 1))
        (if (= size 0) (set! back nil))
        value
        )
    (define (dequeueBack)
        (define value (caar back))
        (set! back (cdr (car back)))
        (set! size (- size 1))
        (if (= size 0) (set! front nil))
        value
        )
    (define (display)
        (define (iter x)
            (if (nil? x) nil
                (begin
                    (print (caar x))
                    (if (not (nil? (cdr x))) (print ',))
                    (iter (cdr x))
                    )
                )
            )
        (print '[)
        (iter front)
        (print '])
        )
    this
    )

(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define env this)
    (define (iter expr)
        (if (not (eof?)) (begin (eval expr env) (iter (readExpr))))
        )
    (iter (readExpr))
    )
